name: Business Kit
favicon: null
layout_spectrum: 0.50122
typography_spectrum: 1
title: Business Kit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b1aea7'
    - '#7e7c7f'
    - '#120a07'
    - '#51473e'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
